title: ""
logo: "assets/images/Profile_Picture.jpg"
theme: jekyll-theme-minimal
show_downloads: false  # Disable default downloads section
description: "Data Engineer with expertise in engineering, business analytics, and management, using cloud technologies to drive impactful data solutions."

css:
  - /assets/styles.css
